name: FactionsPro
author: Tethered_, edited by VMPE Development Team
description: A Extended Factions plugin. [beta-testing Branch]
version: 2.0.0-beta
main: FactionsPro\FactionMain
api: [3.1.1]
softdepend: ["PureChat", "AntiSpamPro", "EssentialsPE", "EconomyAPI"]
permissions:
  f.command:
    description: "Factions command"
    default: true
